import { Brain, Wrench, FileJson, Image, Scale } from 'lucide-react'
import type { CatalogView, ModelStatusFilter, UrlState } from './types'

export const API_URL = 'https://models.dev/api.json'
export const LOGO_BASE_URL = 'https://models.dev/logos'
export const MODELS_DEV_REPO_URL = 'https://github.com/anomalyco/models.dev'
export const LOBE_ICON_BASE_URL = 'https://unpkg.com/@lobehub/icons-static-svg@latest/icons'
export const PAGE_SIZE = 24
export const SESSION_CACHE_KEY = 'models-dev-plus-cache'
export const MAX_COMPARISON_MODELS = 8
export const COMPARISON_FIELD_COLUMN_REM = 9
export const COMPARISON_MODEL_COLUMN_REM = 12.5

export const PROVIDER_LOBE_ICON_SLUGS: Record<string, string> = {
  '302ai': 'ai302',
  aihubmix: 'aihubmix',
  alibaba: 'alibaba',
  'alibaba-cn': 'alibaba',
  'alibaba-coding-plan': 'alibaba',
  'alibaba-coding-plan-cn': 'alibaba',
  'amazon-bedrock': 'bedrock',
  anthropic: 'anthropic',
  azure: 'azure',
  'azure-cognitive-services': 'azureai',
  baseten: 'baseten',
  cerebras: 'cerebras',
  'cloudflare-ai-gateway': 'cloudflare',
  'cloudflare-workers-ai': 'workersai',
  cohere: 'cohere',
  deepinfra: 'deepinfra',
  deepseek: 'deepseek',
  firepass: 'fireworks',
  'fireworks-ai': 'fireworks',
  friendli: 'friendli',
  'github-copilot': 'githubcopilot',
  'github-models': 'github',
  google: 'google',
  'google-vertex': 'vertexai',
  'google-vertex-anthropic': 'vertexai',
  groq: 'groq',
  huggingface: 'huggingface',
  inception: 'inception',
  inference: 'inference',
  kilo: 'kilocode',
  'kimi-for-coding': 'kimi',
  lmstudio: 'lmstudio',
  minimax: 'minimax',
  'minimax-cn': 'minimax',
  'minimax-cn-coding-plan': 'minimax',
  'minimax-coding-plan': 'minimax',
  mistral: 'mistral',
  modelscope: 'modelscope',
  moonshotai: 'moonshot',
  'moonshotai-cn': 'moonshot',
  morph: 'morph',
  nebius: 'nebius',
  nova: 'nova',
  'novita-ai': 'novita',
  nvidia: 'nvidia',
  'ollama-cloud': 'ollama',
  openai: 'openai',
  opencode: 'opencode',
  'opencode-go': 'opencode',
  openrouter: 'openrouter',
  perplexity: 'perplexity',
  'perplexity-agent': 'perplexity',
  poe: 'poe',
  'qiniu-ai': 'qiniu',
  siliconflow: 'siliconcloud',
  'siliconflow-cn': 'siliconcloud',
  stepfun: 'stepfun',
  submodel: 'submodel',
  'tencent-coding-plan': 'tencent',
  'tencent-tokenhub': 'tencent',
  togetherai: 'together',
  upstage: 'upstage',
  v0: 'v0',
  venice: 'venice',
  vercel: 'vercel',
  xai: 'xai',
  xiaomi: 'xiaomimimo',
  'xiaomi-token-plan-ams': 'xiaomimimo',
  'xiaomi-token-plan-cn': 'xiaomimimo',
  'xiaomi-token-plan-sgp': 'xiaomimimo',
  zai: 'zai',
  'zai-coding-plan': 'zai',
  zenmux: 'zenmux',
  zhipuai: 'zhipu',
  'zhipuai-coding-plan': 'zhipu',
}

export const MODEL_FAMILY_LOBE_ICON_SLUGS: Record<string, string> = {
  baichuan: 'baichuan',
  claude: 'claude',
  'claude-haiku': 'claude',
  'claude-opus': 'claude',
  'claude-sonnet': 'claude',
  command: 'commanda',
  'command-a': 'commanda',
  'dall-e': 'dalle',
  deepseek: 'deepseek',
  'deepseek-flash': 'deepseek',
  'deepseek-flash-free': 'deepseek',
  'deepseek-thinking': 'deepseek',
  devstral: 'mistral',
  codestral: 'mistral',
  'codestral-embed': 'mistral',
  flux: 'flux',
  gemini: 'gemini',
  'gemini-embedding': 'gemini',
  'gemini-flash': 'gemini',
  'gemini-flash-lite': 'gemini',
  'gemini-pro': 'gemini',
  gemma: 'gemma',
  glm: 'chatglm',
  'glm-air': 'chatglm',
  'glm-flash': 'chatglm',
  'glm-free': 'chatglm',
  'glm-z': 'chatglm',
  glmv: 'glmv',
  'gpt-codex': 'codex',
  'gpt-codex-mini': 'codex',
  grok: 'grok',
  'grok-beta': 'grok',
  'grok-vision': 'grok',
  hunyuan: 'hunyuan',
  kimi: 'kimi',
  'kimi-free': 'kimi',
  'kimi-k2.5': 'kimi',
  'kimi-k2.6': 'kimi',
  'kimi-thinking': 'kimi',
  llava: 'llava',
  magistral: 'mistral',
  'magistral-medium': 'mistral',
  'magistral-small': 'mistral',
  mimo: 'xiaomimimo',
  'mimo-flash-free': 'xiaomimimo',
  'mimo-omni-free': 'xiaomimimo',
  'mimo-pro-free': 'xiaomimimo',
  'mimo-v2-omni': 'xiaomimimo',
  'mimo-v2-pro': 'xiaomimimo',
  'mimo-v2.5': 'xiaomimimo',
  'mimo-v2.5-pro': 'xiaomimimo',
  minimax: 'minimax',
  'minimax-free': 'minimax',
  'minimax-m2.5': 'minimax',
  'minimax-m2.7': 'minimax',
  ministral: 'mistral',
  mistral: 'mistral',
  'mistral-embed': 'mistral',
  'mistral-large': 'mistral',
  'mistral-medium': 'mistral',
  'mistral-nemo': 'mistral',
  'mistral-small': 'mistral',
  mixtral: 'mistral',
  'nova-lite': 'nova',
  'nova-micro': 'nova',
  'nova-pro': 'nova',
  openchat: 'openchat',
  pixtral: 'mistral',
  qwen: 'qwen',
  'qwen-free': 'qwen',
  'qwen3.5': 'qwen',
  'qwen3.6': 'qwen',
  recraft: 'recraft',
  sora: 'sora',
  step: 'stepfun',
  voxtral: 'mistral',
  yi: 'yi',
}

export const MODEL_FAMILY_LOBE_ICON_PREFIXES = [
  ['claude-', 'claude'],
  ['deepseek-', 'deepseek'],
  ['gemini-', 'gemini'],
  ['gpt-codex', 'codex'],
  ['glm-', 'chatglm'],
  ['grok-', 'grok'],
  ['kimi-', 'kimi'],
  ['mimo-', 'xiaomimimo'],
  ['minimax-', 'minimax'],
  ['mistral-', 'mistral'],
  ['nova-', 'nova'],
  ['qwen', 'qwen'],
] as const

export const MODEL_TEXT_LOBE_ICON_MATCHERS = [
  { slug: 'claude', terms: ['claude'] },
  { slug: 'codex', terms: ['codex'] },
  { slug: 'dalle', terms: ['dall-e', 'dalle'] },
  { slug: 'deepseek', terms: ['deepseek', 'deepseek-ai'] },
  { slug: 'doubao', terms: ['doubao'] },
  { slug: 'flux', terms: ['flux'] },
  { slug: 'gemini', terms: ['gemini'] },
  { slug: 'gemma', terms: ['gemma'] },
  { slug: 'glmv', terms: ['glmv'] },
  { slug: 'chatglm', terms: ['chatglm', 'glm'] },
  { slug: 'grok', terms: ['grok'] },
  { slug: 'hunyuan', terms: ['hunyuan'] },
  { slug: 'kimi', terms: ['kimi'] },
  { slug: 'llava', terms: ['llava'] },
  { slug: 'minimax', terms: ['minimax'] },
  { slug: 'mistral', terms: ['mistral', 'mixtral', 'codestral', 'devstral', 'pixtral', 'ministral', 'magistral', 'voxtral'] },
  { slug: 'nova', terms: ['amazon nova'] },
  { slug: 'openchat', terms: ['openchat'] },
  { slug: 'qwen', terms: ['qwen'] },
  { slug: 'recraft', terms: ['recraft'] },
  { slug: 'sora', terms: ['sora'] },
  { slug: 'stepfun', terms: ['stepfun', 'stepfun-ai'] },
  { slug: 'xiaomimimo', terms: ['mimo', 'xiaomi mimo'] },
  { slug: 'baichuan', terms: ['baichuan'] },
  { slug: 'yi', terms: ['yi'] },
] as const

export const LOBE_COLOR_ICON_SLUGS = new Set([
  'ai302',
  'aihubmix',
  'alibaba',
  'azure',
  'azureai',
  'baichuan',
  'bedrock',
  'cerebras',
  'chatglm',
  'claude',
  'cloudflare',
  'codex',
  'cohere',
  'commanda',
  'dalle',
  'deepinfra',
  'deepseek',
  'doubao',
  'fireworks',
  'gemini',
  'gemma',
  'glmv',
  'google',
  'huggingface',
  'hunyuan',
  'kimi',
  'llava',
  'minimax',
  'mistral',
  'modelscope',
  'morph',
  'nova',
  'novita',
  'nvidia',
  'perplexity',
  'poe',
  'qiniu',
  'siliconcloud',
  'sora',
  'stepfun',
  'submodel',
  'tencent',
  'together',
  'upstage',
  'venice',
  'vertexai',
  'workersai',
  'yi',
  'zhipu',
])

export const CAPABILITIES = [
  { key: 'reasoning', label: 'Reasoning', icon: Brain },
  { key: 'tool_call', label: 'Tool Call', icon: Wrench },
  { key: 'structured_output', label: 'Structured Output', icon: FileJson },
  { key: 'attachment', label: 'Attachment', icon: Image },
  { key: 'open_weights', label: 'Open Weights', icon: Scale },
] as const

export const URL_KEYS = {
  search: 'q',
  provider: 'provider',
  family: 'family',
  caps: 'caps',
  cap: 'cap',
  inputModality: 'in',
  outputModality: 'out',
  sort: 'sort',
  view: 'view',
  status: 'status',
  page: 'page',
  model: 'model',
  modelProvider: 'modelProvider',
  compare: 'compare',
} as const

export const CATALOG_VIEWS = new Set<CatalogView>(['cards', 'table'])
export const STATUS_FILTERS = new Set<ModelStatusFilter>(['all', 'stable', 'alpha', 'beta', 'deprecated'])

export const DEFAULT_URL_STATE: UrlState = {
  search: '',
  provider: 'all',
  family: 'all',
  caps: [],
  inputModality: [],
  outputModality: [],
  sortBy: 'lastUpdated',
  view: 'cards',
  status: 'all',
  page: 1,
  modelId: null,
  modelProviderId: null,
  compare: [],
}

export const SORT_KEYS = new Set([
  'lastUpdated',
  'lastUpdatedAsc',
  'releaseDate',
  'releaseDateAsc',
  'name',
  'nameDesc',
  'contextSize',
  'contextSizeAsc',
  'outputLimit',
  'outputLimitAsc',
  'inputCost',
  'inputCostDesc',
  'outputCost',
  'outputCostDesc',
])
